packages:
    - config
    - packages/*
    - sites/*
catalog:
    '@changesets/cli': ^2.27.1
    '@content-thing/memdb': ^0.0.10
    '@svelte-thing/components': ^0.0.44
    '@svelte-thing/css': ^0.0.2
    '@svelte-thing/rune-components': ^0.0.14
    '@sveltejs/adapter-auto': ^4.0.0
    '@sveltejs/kit': ^2.16.0
    '@sveltejs/vite-plugin-svelte': ^5.0.0
    '@types/node': ^20.10.5
    content-thing: ^0.0.40
    eslint: ^9.19.0
    eslint-config-prettier: ^10.0.0
    eslint-plugin-svelte: ^2.46.1
    globals: ^15.14.0
    prettier: ^3.4.0
    prettier-plugin-svelte: ^3.3.3
    publint: ^0.3.2
    svelte: ^5.19.0
    svelte-check: ^4.1.0
    typescript: ^5.7.0
    typescript-eslint: ^8.22.0
    vite: ^6.0.11
    vitest: ^3.0.4
    wireit: ^0.14.10
